import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("hospital.csv")
print(df.head())
print(df.info())
print(df.describe())
print("Average Age:")
print(df["Age"].mean())
print("Maximum BP:")
print(df["BP"].max())
print("Maximum Sugar:") 
print(df["Sugar"].max())
print("Average Bill:")
print(df["Bill"].mean())
print("Patient with the highest bill:")
highest_bill = df.loc[df["Bill"].idxmax()]
print("Patient with the highest bill:")
print(highest_bill["Patient"])
print("Bill:", highest_bill["Bill"])
print("Patient with the highest sugar level:")
highest_sugar = df.loc[df["Sugar"].idxmax()]
print(highest_sugar["Patient"])
print("Average Bill by Disease:")
val=df.groupby("Disease")["Bill"].mean()
print(val)
print(df.loc[df["Disease"]=="Diabetes",["Patient"]])
plt.plot(df["Patient"], df["Age"], color="green", linewidth=2)
plt.title("Age of Patients")
plt.xlabel("Age")   
plt.show()
plt.bar(val.index, val.values, color="orange")
plt.title("Average Bill by Disease")
plt.xlabel("Disease")   
plt.ylabel("Average Bill")
plt.show()
disease_count = df["Disease"].value_counts()
plt.pie(
    disease_count,
    labels=disease_count.index,
    autopct="%1.1f%%")
plt.title("Disease Distribution")
plt.show()
plt.hist(df["Age"], bins=10, color="blue", edgecolor="black")
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()
plt.scatter(df["Age"], df["Sugar"], color="red")
plt.title("Age vs Sugar Level")
plt.xlabel("Age")   
plt.ylabel("Sugar Level")
plt.show()